### ISSUE TITLE
Error: No configuration provided for styles.scss

### ISSUE THREAD

**Issue by karolsw3** [ericalli/static-site-boilerplate#38]
**What's wrong?**
When I'm running `npm run start` after setting up the project with wizard, I'm getting this error:

`Error: No configuration provided for /Users/username/Documents/GitHub/repo-name/src/stylesheets/styles.scss
    at module.exports (/Users/username/Documents/GitHub/repo-name/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at searchForConfig.then.then.config (/Users/username/Documents/GitHub/repo-name/node_modules/stylelint/lib/getConfigForFile.js:55:15)`

**To Reproduce**
1. Run `npm install`
2. Run `npm run start`
4. See the error

**Expected behavior**
Error not showing up.

**Screenshots**
<img width="570" alt="Screenshot 2019-12-18 at 22 16 23" src="https://user-images.githubusercontent.com/1695865/71123917-0c3ff680-21e4-11ea-952b-7ef4464c8afb.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.1.0

I've tried installing and running it two times already.

**Comment by LMulvey** [comment]
Add a `.stylelintrc.json` file to the _**root**_ of your project with the following contents: 

```
{
  "extends": "stylelint-config-standard"
}
```

Not sure when this changed but this fixed the issue for me!

**Comment by Maedea9** [comment]
Hello, do I have to create a new file called stylelintrc.js (js as JavaScript?) o is it the same stylelintrc.json I already have? Thanks
