### ISSUE TITLE
Fresh install npm install error

### ISSUE THREAD

**Issue by EslamSaid** [ericalli/static-site-boilerplate#50]
node -v v14.2.0
npm -v6.14.5

> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@14.2.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated:
      Use GetBackingStore. See http://crbug.com/v8/9908.
      [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/richardroe/Library/Caches/node-gyp/14.2.0/include/node/v8.h:5202:3: note:
      'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/richardroe/Library/Caches/node-gyp/14.2.0/include/node/v8config.h:402:39: note:
      expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/richardroe/Documents/static-site-boilerplate/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> sharp@0.22.1 install /Users/richardroe/Documents/static-site-boilerplate/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/richardroe/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.2.0 runtime=node arch=x64 libc= platform=darwin)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc:130:19: error: no matching member function for call to 'Set'
        channels->Set(i, channelStat);
        ~~~~~~~~~~^~~
/Users/richardroe/Library/Caches/node-gyp/14.2.0/include/node/v8.h:3639:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/richardroe/Library/Caches/node-gyp/14.2.0/include/node/v8.h:3642:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
1 error generated.
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/richardroe/Documents/static-site-boilerplate/node_modules/sharp
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richardroe/.npm/_logs/2020-05-14T23_42_56_422Z-debug.log

**Comment by EslamSaid** [comment]
I fixed the issue by using node v12 instead of v14, how ever there is an issue with live server, it's not reloading the changes at all despite the compiling is successful, any suggestions ?

**Comment by ericalli** [comment]
Working on updating SSB to support up to Node v14. Will keep you posted.

**Comment by kriiv** [comment]
Any news on this?

**Comment by kyds3k** [comment]
Did this get resolved? I just tried a fresh install using node 14 and got a CRAZY long list of errors. Too long for me to paste here or on pastebin.

**Comment by kyds3k** [comment]
Any update on this? I'm getting a fail to build on node v15.15.1:

`gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adamdarby/sandbox/static-site-boilerplate/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/Users/adamdarby/.nvm/versions/node/v14.15.1/bin/node" "/Users/adamdarby/sandbox/static-site-boilerplate/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/adamdarby/sandbox/static-site-boilerplate/node_modules/node-sass
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adamdarby/.npm/_logs/2021-06-13T07_41_21_426Z-debug.log`

**Comment by ericalli** [comment]
@kyds3k I think I've found the issue here. Node Sass v5+ is required for Node v15 support. I'll update this package and test it out shortly. If you want to try this yourself, i think it should be a quick fix. Just edit the `package.json` file on line 63, change:

`"node-sass": "^4.12.0",`

to 

`"node-sass": "^5.0.0",`

Then run `npm install`. Let me know if that does the trick.

**Comment by kyds3k** [comment]
@ericalli that did the trick! Thank you!
