### ISSUE TITLE
Webpack build error

### ISSUE THREAD

**Issue by tapkain** [ericalli/static-site-boilerplate#7]
---
name: Webpack build error
about: clean-webpack-plugin dist has been removed error
---

**To Reproduce**
1. npm install
2. follow install guide
3. npm run start

> npm run start
> static-site-boilerplate@1.0.0 start /Users/eugeveli/Desktop/myProj/wallpapers/wallpapers.site
> cross-env NODE_ENV=development webpack-dev-server --config ./config/webpack.config.js

clean-webpack-plugin: /Users/eugeveli/desktop/myproj/wallpapers/wallpapers.site/dist has been removed.
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (net.js:1255:14)
    at listenInCluster (net.js:1303:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1442:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1282:8)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! static-site-boilerplate@1.0.0 start: `cross-env NODE_ENV=development webpack-dev-server --config ./config/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the static-site-boilerplate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eugeveli/.npm/_logs/2019-01-11T15_24_44_405Z-debug.log

**Desktop
[2019-01-11T15_31_24_839Z-debug.log](https://github.com/ericalli/static-site-boilerplate/files/2750166/2019-01-11T15_31_24_839Z-debug.log)
:**
 - OS: macOS 10.14

**Comment by JayBee007** [comment]
@tapkain Well it clearly says `Error: listen EADDRINUSE: address already in use 127.0.0.1:8000`, the port `8000` is already running something. You need to kill that task first.

**Comment by taimursaeed** [comment]
In the site.config.js the default port is 8000. Sometimes I have multiple projects running which are already using port 8000. Is there an option to specify a different port with the help of CLI like npm run start --port 8080?

**Comment by BenceSzalai** [comment]
You can modify the default port in `config/site.config.js`.
