### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by knzone** [ericalli/static-site-boilerplate#81]
> node -v 16.5.0
> npm -v 8.8.0

Hello, `npm install` fails with error:

...
npm ERR! code 1
npm ERR! path C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\bdied\\Documents\\Projekte\\boilerplate\\static-site-boilerplate\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bdied\\Documents\\Projekte\\boilerplate\\static-site-boilerplate\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\bdied\Documents\Projekte\boilerplate\static-site-boilerplate\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
...

Any ideas why?

**Comment by StevenLove** [comment]
I had a somewhat similar error trying to run `npm install`, and my error was fixed by updating python.
I'm on mac so I ran `brew install python3` and then `npm install` worked. 

From your log:
`npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];`
and
`
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
`
According to [python docs](https://docs.python.org/3/whatsnew/3.0.html) in version 3.0 they switched from a syntax where you call print **without** parentheses to one where you call print **with** parentheses. Seems like this is consistent with your install problem being caused by having the wrong python version.

Good luck!

**Comment by shenef** [comment]
Same problem here, my Python is already on the latest version (3.10.4).
npm 8.9.0
node 17.9.0

**Comment by binakot** [comment]
Same here on archlinux.

Just `git clone` repo and run `npm i`.

```
10469 verbose Linux 6.1.7-arch1-1
10470 verbose node v16.18.1
10471 verbose npm  v8.19.2
10472 error code 1
10473 error path /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/node-sass
10474 error command failed
10475 error command sh -c -- node scripts/build.js
10476 error Building: /home/binakot/.nvm/versions/node/v16.18.1/bin/node /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
10477 error gyp info it worked if it ends with ok
10477 error gyp verb cli [
10477 error gyp verb cli   '/home/binakot/.nvm/versions/node/v16.18.1/bin/node',
10477 error gyp verb cli   '/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/node-gyp/bin/node-gyp.js',
10477 error gyp verb cli   'rebuild',
10477 error gyp verb cli   '--verbose',
10477 error gyp verb cli   '--libsass_ext=',
10477 error gyp verb cli   '--libsass_cflags=',
10477 error gyp verb cli   '--libsass_ldflags=',
10477 error gyp verb cli   '--libsass_library='
10477 error gyp verb cli ]
10477 error gyp info using node-gyp@3.8.0
10477 error gyp info using node@16.18.1 | linux | x64
10477 error gyp verb command rebuild []
10477 error gyp verb command clean []
10477 error gyp verb clean removing "build" directory
10477 error gyp verb command configure []
10477 error gyp verb check python checking for Python executable "python2" in the PATH
10477 error gyp verb `which` failed Error: not found: python2
10477 error gyp verb `which` failed     at getNotFoundError (/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:13:12)
10477 error gyp verb `which` failed     at F (/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:68:19)
10477 error gyp verb `which` failed     at E (/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:80:29)
10477 error gyp verb `which` failed     at /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:89:16
10477 error gyp verb `which` failed     at /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/isexe/index.js:42:5
10477 error gyp verb `which` failed     at /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/isexe/mode.js:8:5
10477 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
10477 error gyp verb `which` failed  python2 Error: not found: python2
10477 error gyp verb `which` failed     at getNotFoundError (/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:13:12)
10477 error gyp verb `which` failed     at F (/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:68:19)
10477 error gyp verb `which` failed     at E (/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:80:29)
10477 error gyp verb `which` failed     at /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/which/which.js:89:16
10477 error gyp verb `which` failed     at /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/isexe/index.js:42:5
10477 error gyp verb `which` failed     at /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/isexe/mode.js:8:5
10477 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
10477 error gyp verb `which` failed   code: 'ENOENT'
10477 error gyp verb `which` failed }
10477 error gyp verb check python checking for Python executable "python" in the PATH
10477 error gyp verb `which` succeeded python /usr/bin/python
10477 error gyp ERR! configure error 
10477 error gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
10477 error gyp ERR! stack   File "<string>", line 1
10477 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
10477 error gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10477 error gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
10477 error gyp ERR! stack 
10477 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:402:12)
10477 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
10477 error gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
10477 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
10477 error gyp ERR! System Linux 6.1.7-arch1-1
10477 error gyp ERR! command "/home/binakot/.nvm/versions/node/v16.18.1/bin/node" "/home/binakot/_repos/waliot/firstmk-landing-page/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
10477 error gyp ERR! cwd /home/binakot/_repos/waliot/firstmk-landing-page/node_modules/node-sass
10477 error gyp ERR! node -v v16.18.1
10477 error gyp ERR! node-gyp -v v3.8.0
10477 error gyp ERR! not ok 
10477 error Build failed with error code: 1
10478 verbose exit 1
```

```bash
$ node -v
v16.18.1

$ npm -v
8.19.2

$ python --version
Python 3.10.9

$ python3 --version
Python 3.10.9
```

**Comment by binakot** [comment]
Btw if I switch to Node 14, it will works!

I think maintainer should remove current `package-lock.json`, update Node to 16 and try to run project again.
